import {
  MANIFEST_SCHEMA_V2_URI,
  MODULE_SCHEMA_V2_URI,
  type EditorProject,
} from "./types";

export const EDITOR_VERSION = "0.3.0";

export function createDefaultProject(): EditorProject {
  return {
    editor_version: 2,
    manifest: {
      $schema: MANIFEST_SCHEMA_V2_URI,
      format_version: "2.0",
      id: "untitled.investigation",
      version: "0.1.0",
      title: "无题调查",
      author: "",
      description: "",
      system: "COC 第七版",
      era: "1920s",
      language: "zh-CN",
      license: "",
      homepage: "",
      min_engine_version: "1.0.0",
      entry: "module.json",
      keeper_document: "keeper.md",
      theme: "theme.json",
      lorebook: null,
      capabilities: [],
      tags: [],
      created_with: `TRPG Mod Editor ${EDITOR_VERSION}`,
      checksums: {},
    },
    module: {
      $schema: MODULE_SCHEMA_V2_URI,
      format_version: "2.0",
      entry_scene_id: "opening_scene",
      opening_prompt: "调查员抵达故事开始的地点。",
      npcs: {},
      scenes: {
        opening_scene: {
          name: "开场地点",
          aliases: [],
          description: "在这里写下玩家第一次进入场景时能够感知到的内容。",
          exits: [],
          npcs_present: [],
          encounters: [],
          tags: ["开场"],
          document: null,
          asset_id: null,
          extensions: {},
        },
      },
      clues: {},
      endings: {},
      rules: {},
      assets: { npcs: {}, scenes: {}, clues: {} },
      initial_state: {
        pc: {
          name: "",
          occupation: "",
          hp: 11,
          max_hp: 11,
          san: 65,
          max_san: 65,
          attributes: {},
          skills: {},
          inventory: [],
          conditions: [],
          psychological_profile: {
            traits: [],
            key_relationships: [],
            phobias: [],
            manias: [],
          },
          extensions: {},
        },
        known_clue_ids: [],
        flags: {},
        case_clocks: {},
        private_memory: {
          goals_and_plans: "",
          hidden_facts: {},
          inference_notes: "游戏刚开始。所有 NPC 秘密均未揭示。",
        },
        extensions: {},
      },
      clue_links: [],
      extensions: {},
      progression: { essential_clue_ids: [] },
    },
    keeperDocument: "# 守秘人正文\n\n在这里记录节奏、扮演建议和失败推进。\n",
    theme: {
      title: "无题调查",
      subtitle: "A TRPG Investigation",
      colors: {
        bg: "#14100c",
        text: "#ddd0bc",
        gold: "#c8a24e",
      },
    },
    lorebook: null,
  };
}
